name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci:
    # Ubuntu 24 has vips 8.15, but Ubuntu 22 only has vips 8.12.
    # We want at least version 8.15 because >= 8.15 supports the revalidate feature.
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby-version: ['3.2.2']
        node: ['20']
        redis-version: [7]
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Install vips
        run: sudo apt install -y libvips-tools
      - name: Check vips version
        run: vips --version
      - name: Install libxslt for nokogiri gem (required for version < 1.11)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Run CI task
        run: bundle exec rake triclops:ci
